### PR TITLE
Port upstream NumPy 1.25.0 

### PR DESCRIPTION
**Pull request by andreittr**
This change set ports the popular NumPy python extension to unikraft at upstream version 1.25.0, along with necessary compatibility patches.

This is part of a larger work and depends on Python 3.10
- https://github.com/unikraft/lib-python3/pull/15

and all its dependencies; plus a patch to register numpy modules:
- https://github.com/unikraft/lib-python3/pull/16

In addition:
- https://github.com/unikraft/lib-intel-intrinsics/pull/3
- https://github.com/unikraft/unikraft/pull/983
- https://github.com/unikraft/lib-musl/pull/64
- https://github.com/unikraft/lib-musl/pull/65

Libs used for build:
```
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-libcxx
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-libcxxabi
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-libunwind
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-intel-intrinsics
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-compiler-rt
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-musl
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-libffi
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-lwip
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-bzip2
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-sqlite
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-openssl
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-libuuid
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-zlib
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-python3
LIBS-y := $(LIBS-y):$(UK_LIBS)/lib-python-numpy
```

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good @andreittr, thank you.
I'll add the tag after the [`x86 instrinsics`](https://github.com/unikraft/lib-intel-intrinsics/pull/3) pr is merged.

**Review by RaduNichita — APPROVED** [review]
All good with me. I tested with gcc12 and clang15. Thanks @andreittr for this monstrous effort!

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Comment by RaduNichita** [comment]
One small request, @andreittr: could you please add compiler version checks in the Makefile.uk (similar to what it is in the Unikraft [Makefile](https://github.com/unikraft/unikraft/blob/staging/Makefile#L693)). 

You can see a similar discussion [here](https://github.com/unikraft/lib-libgo/pull/7#issuecomment-1669746335).

**Comment by andreittr** [comment]
> One small request, @andreittr: could you please add compiler version checks in the Makefile.uk (similar to what it is in the Unikraft [Makefile](https://github.com/unikraft/unikraft/blob/staging/Makefile#L693)).
> 
> You can see a similar discussion [here](https://github.com/unikraft/lib-libgo/pull/7#issuecomment-1669746335).

Do we have versions that are known to be too old to build numpy but newer than the ones in main Unikraft? Because I wouldn't want to error out just on a guess/the extent to which we've tested.

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by andreittr** [comment]
> Do we have versions that are known to be too old to build numpy but newer than the ones in main Unikraft? Because I wouldn't want to error out just on a guess/the extent to which we've tested.

Re: this, currently investigating an issue building with gcc 11, but it has to do with x86 intrinsics more broadly; so not really a numpy issue, will fix in `lib-intel-intrinsics`. Rootfs build is [also ok](https://github.com/unikraft/lib-python-shapely/pull/1#issuecomment-1677371812). I think this can be merged.

edit: intrinsics fix in following PR:
- https://github.com/unikraft/lib-intel-intrinsics/pull/4
also, related to compiler version checking when building numpy:
- https://github.com/unikraft/lib-libcxx/pull/33

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
